### ISSUE TITLE
Validate COG bounding box

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-stac-ingestor#51]
We had a couple datasets (see this [issue](https://github.com/orgs/NASA-IMPACT/projects/51/views/6?pane=issue&itemId=14371691))  where the COGs were created with the incorrect bounding box order. Bounding box should be in this format `xmin, ymin, xmax, ymax` but we've seen the order of `ymin/ymax` reversed which causes 404 errors in the front end when the tile is not found. We should validate the bounding box to ensure it's in the correct format.

**Comment by moradology** [comment]
Would it be better to just insert the correct value at this point to avoid any extra hassles or do we want a human to be in the loop, so to speak?

**Comment by j08lue** [comment]
> It is the actual tif whose metadata is wrong

Just to be sure we agree here - GeoTIFF with an origin in the lower-left corner are as valid as the most common case where the origin is upper-left and should render correctly in TiTiler and other software, as long as the transform corresponds to the orientation of the raster. https://www.perrygeo.com/python-affine-transforms.html

I think the problem here was that the bbox info in STAC was wrong, not that TiTiler does not handle Y-flipped rasters well, no?

People sometimes compute bboxes by taking the coordinates of the first/last pixel in the raster along the two dimensions and that obviously fails when the raster is flipped. The very simple fix is to min/max the coordinates to be sure they are in the right order for the bbox.

https://github.com/NASA-IMPACT/veda-data-pipelines/issues/235#issuecomment-1468832083

**Comment by moradology** [comment]
It looks like the appropriate place to fix this is upstream via geojson-pydantic: https://github.com/developmentseed/geojson-pydantic/pull/114

**Comment by vincentsarago** [comment]
> I think the problem here was that the bbox info in STAC was wrong, not that TiTiler does not handle Y-flipped rasters well, no?

In this case I'm pretty sure it was the transform of the geotiff which was wrong. This resulted in TiTiler creating a TileJSON with wrong bbox and thus breaking the frontend because MapboxGL (or any client) won't be able to understand this weird bbox

**Comment by moradology** [comment]
If that's right, validation isn't obviously available to prevent the observed bug going forward. At least there will be a bit more sanity checking on OS tools that everyone uses 🤷
