### ISSUE TITLE
Fix: Can't publish items to existing collection that doesn't follow the id naming convention

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-stac-ingestor#67]
# Description
The validation rule for the `collection_id` field in the dataset definition allows for only lowercase characters with optional hyphens.
However, some of our older collections still have an id that doesn't follow this convention which makes it impossible to ingest items to such a collection using the `/dataset/publish` endpoint.

# Options
- [ ] Get rid of the validation altogether
- [ ] Add an extra field in the dataset definition to specify that this is an existing collection, in which case you don't do the validation. Another positive consequence of this is that the collection won't get updated each time a dataset is published
- [ ] Provide a way to bypass validation for special cases like this

Probably one of 2 or 3?

**Comment by j08lue** [comment]
> Another positive consequence of this is that the collection won't get updated each time a dataset is published

I found it odd that I could in the same call add items to an existing collection and change its metadata - although you will often want to change temporal and spatial extent. Maybe we could in the future infer extents from the data instead? A bit more auto-magic for "spatio-temporal" would not hurt.

Otherwise, I would be in favor of keeping the validation, but allowing one exception, which is the collection name.

Or yet another option: Update all existing collection names to match our convention. That would require us to update a few configs here and there, but **now is the time for that** - while we are still on `staging`. And we will not want this naming mess in production anyways.

**Comment by slesaad** [comment]
fixed in https://github.com/NASA-IMPACT/veda-stac-ingestor/pull/77
